openapi: 3.0.3
info:
  title: STD23071 - TD3
  version: '1.0.3'
servers:
  - url: https://localhost.std23071.com
paths:
  /meal:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
      responses:
        200:
          description: List of meal
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateMeal'
        required: true
      responses:
        200:
          description: List of created meal
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Meal'
        required: true
      responses:
        200:
          description: List of updated meal
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    delete:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MealIdentifier'
        required: true
      responses:
        200:
          description: List of deleted meal
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
  /customers/{customerId}/orders:
    get:
      tags:
        - Order
      summary: Get customer's orders
      operationId: getOrdersbyCustomerId
      responses:
        200:
            description: List of orders
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Order'
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Order'
        required: true
      responses:
        200:
          description: List of updated order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Order'
        required: true
      responses:
        200:
          description: List of created meal
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
components:
  schemas:
    Meal:
      allOf:
        - $ref: '#/components/schemas/MealIdentifier'
        - $ref: '#/components/schemas/CreateMeal'
    MealIdentifier:
      type: object
      properties:
        id:
          type: string
    CreateMeal:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
    Order:
      type: object
      properties:
        reference:
          type: string
        meals:
          type: array
          items:
            type: object
            properties:
              quantity:
                type: integer
              meal:
                $ref: '#/components/schemas/Meal'
        orderDatetime:
          type: string
          format: date-time